// anything that we add here will display everywher // this is an one upper layer file // its main entry point of the application // in most cases we will use the nav bar or the footer
// in a nutshell if we want to add something that should stay consistent across all routes such as --> navbar --> routes --> footer --> redux toolkit wrapper should be plased in here
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const res = await fetch("https://api.github.com", {
    cache:"no-store", // support for dynamic data on every request  // by default all the data are static //  no-store means on every request we will bypass cashing and fetch new data
    next: {
      revalidate: 5 // will validate new data on every 5 second on request not automatically
    }
  });
  const data = await res.json();
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>{data.current_user_url}</h1>
        {children}
      </body>
    </html>
  )
}
